apiVersion: v1
kind: Service
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    service: dtlabs-apigateway-service
  name: dtlabs-apigateway-service
spec:
  ports:
  - name: "9999"
    port: 9999
    targetPort: 9999
  selector:
    pod: dtlabs-apigateway-service
  type: NodePort
