eureka:
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    hostname: localhost:${server.port}
    prefer-ip-address: true
    ip-address: localhost
    non-secure-port: ${server.port}
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 15
  client:
    region: default
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:8761/eureka/
