eureka:
  instance:
    instance-id: localhost:${server.port}
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
  client:
    region: default
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
