apiVersion: v1
kind: Service
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    service: dtlabs-registration-service
  name: dtlabs-registration-service
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8090
  selector:
    pod: dtlabs-registration-service
  type: NodePort
status:
  loadBalancer: {}
