apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    deployment: labs-registration-service
  name: labs-registration-service-deployment
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        pod: labs-registration-service
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        envFrom:
        - configMapRef:
            name: labs-cm  
        image: labs/labs-registration-service
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "0.3"
          requests:
            cpu: "0.3"            
        name: labs-registration-service-container
        ports:
        - containerPort: 8090
      restartPolicy: Always
#      initContainers:
#      - name: init-mariadb-labs
#        image: busybox
#        command: ['sh', '-c', 'until nslookup mariadb-labs; do date +"%T"; echo waiting for mariadb-labs; sleep 2; done;']
status: {}
