apiVersion: v1
kind: Service
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    service: mariadb-labs
  name: mariadb-labs
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    pod: mariadb-labs
  type: NodePort
status:
  loadBalancer: {}
