apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    deployment: mariadb-labs
  name: mariadb-labs
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        pod: mariadb-labs
    spec:
      containers:
        - image: mariadb:10.1       
          envFrom:
          - configMapRef:
              name: labs-cm         
          imagePullPolicy: IfNotPresent 
          resources:
            limits:
              cpu: "0.3"
            requests:
              cpu: "0.3"               
          name: mariadb-labs-container
          ports:
          - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}
