apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: labs-apigateway-service
  namespace: default

spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: labs-apigateway-service
  targetCPUUtilizationPercentage: 50      