info:
  id: ${spring.application.name}

server:
  port: ${PORT:9999}
     
zuul:
  ignored-services: '*'
#  ignored-patterns: 
  routes:
    labs-registration-service: 
      path: /registration-service/**
      service-id: labs-registration-service
    labs-data-mgmt-service: 
      path: /data-mgmt-service/**
      service-id: labs-data-mgmt-service
        
  
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

