logging:
  level:
    io.dtlabs.data.mgmt: debug

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    registry-fetch-interval-seconds: 5

services: 
  mongodb: 
    name: dtlabs-mongo
  objectstorage:
    username: ${vcap.services.dtlabs-object-storage.credentials.username}
    password: ${vcap.services.dtlabs-object-storage.credentials.password}
    auth_url: ${vcap.services.dtlabs-object-storage.credentials.auth_url}/tokens
    tenantid: ${vcap.services.dtlabs-object-storage.credentials.tenantId}
    tenantname: ${vcap.services.dtlabs-object-storage.credentials.tenantName}