spring: 
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE}
    
file: 
  save: 
    dir: /data 

eureka:
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    hostname: ${spring.application.name}
    prefer-ip-address: true
    ip-address: ${spring.application.name}
    non-secure-port: ${server.port}
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 15
  client:
    region: default
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://${application.username}:${application.password}@${DISCOVERY_NAME}:8761/eureka/