eureka: 
  client:
    enabled: false
    
spring: 
  data:
    mongodb:
      host: ${DTLABS_MONGO_SERVICE_HOST:dtlabs-mongo}
      port: ${DTLABS_MONGO_SERVICE_PORT:27017}
      username: ${DTLABS_MONGO_USERNAME:datamgmt}
      password: ${DTLABS_MONGO_PASSWORD:datamgmt}
      database: ${DTLABS_MONGO_DBNAME:datamgmt}
    
file: 
  save: 
    dir: /test