logging:
  level:
    io.labs.registration: debug
     
spring:
  datasource:
    initialize: true
    platform: h2
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    initial-size: 1
    maximum-pool-size: 2
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration

eureka:
  instance:
    instance-id: localhost:${server.port}
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
  client:
    region: default
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
mailing: 
  from : labs@labs.io
  to:
    list: 
    - limjh82@sk.com
    - 1600078@partner.skcc.com
    - sanghoonhan@sk.com
    - tonite31@sk.com 
    - blingeee@sk.com
    - hunkee1017@sk.com 
    - 1000jaeh@sk.com 
  subject: Test 메일입니다.
  text: Test 메일입니다.
  
hipchat-noti:
  color: green
  message: Test 알림입니다.
  notify: false
  message_format : text
  url : 
  
  

    
  
  