logging:
  level:
    io.dtlabs.registration: debug
    
spring: 
  session:
    store-type: redis
  
services: 
  datasource: 
    name: mariadb-dtlabs
    initial-size: 1
    maximum-pool-size: 2
    max-wait-time: 3000
  redis: 
    name: dtlabs-redis
  
    
mailing: 
  from : dtlabs@dtlabs.io
  to:
    list: 
    - limjh82@sk.com
    - 1600078@partner.skcc.com
    - sanghoonhan@sk.com
    - tonite31@sk.com 
    - blingeee@sk.com
    - hunkee1017@sk.com 
    - 1000jaeh@sk.com 
  subject: Test 메일입니다.
  text: Test 메일입니다.
  
hipchat-noti:   
  color: green
  message: Test 알림입니다.
  notify: false
  message_format: text
  
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    registry-fetch-interval-seconds: 5
