spring:
  datasource:
    initialize: false

eureka:
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    prefer-ip-address: true
    ip-address: ${CF_INSTANCE_IP}
    non-secure-port: ${CF_INSTANCE_PORT}
  client:
    region: default
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${vcap.services.dtlabs-discovery-service.credentials.uri}/eureka/
      
      