logging:
  level:
    io.dtlabs.registration: debug

spring:
  datasource:
    initialize: true
    platform: h2
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    initial-size: 1
    maximum-pool-size: 2
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration

eureka:
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    hostname: localhost:${server.port}
    prefer-ip-address: true
    ip-address: localhost
    non-secure-port: ${server.port}
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 15
  client:
    region: default
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
mailing: 
  from : dtlabs@dtlabs.io
  to:
    list: 
    - limjh82@sk.com
    - 1600078@partner.skcc.com
    - sanghoonhan@sk.com
    - tonite31@sk.com 
    - blingeee@sk.com
    - hunkee1017@sk.com 
    - 1000jaeh@sk.com 
  subject: Test 메일입니다.
  text: Test 메일입니다.
  
hipchat-noti:
  color: green
  message: Test 알림입니다.
  notify: true
  message_format : text
  url : 