eureka: 
  client: 
    enabled: false
    
logging:
  level:
    io.labs.registration: debug
     
spring:
  datasource:
    url: jdbc:mariadb://${MARIADB_LABS_SERVICE_HOST:mariadb-labs}:${MARIADB_LABS_SERVICE_PORT:3306}/${MYSQL_DATABASE:registration}
    username: ${MYSQL_USER:registration}
    password: ${MYSQL_PASSWORD:registration}
    driver-class-name: org.mariadb.jdbc.Driver
    initial-size: 1
    maximum-pool-size: 1
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
      
mailing: 
  from : labs@labs.io
  to:
    list: 
    - limjh82@sk.com
    - 1600078@partner.skcc.com
    - sanghoonhan@sk.com
    - tonite31@sk.com 
    - blingeee@sk.com
    - hunkee1017@sk.com 
    - 1000jaeh@sk.com 
  subject: Test 메일입니다.
  text: Test 메일입니다.
  
hipchat-noti:
  color: green
  message: Test 알림입니다.
  notify: false
  message_format : text
  url : 
  

    
  
  