spring:
  session:
    store-type: redis

services: 
  datasource: 
    name: mariadb-dtlabs
    initial-size: 1
    maximum-pool-size: 5
    max-wait-time: 3000
  redis: 
    name: dtlabs-redis
    
mailing: 
  from : dtlabs@dtlabs.io
  to:
    list: 
    - limjh82@sk.com
    - 1600078@partner.skcc.com
    - sanghoonhan@sk.com
    - tonite31@sk.com 
    - blingeee@sk.com
    - hunkee1017@sk.com 
    - 1000jaeh@sk.com 
  subject: DTLABS 과정에 신청하셨습니다.
  text: DTLABS 포털에서 확인해주세요.

hipchat-noti:
  color: red
  message: DTLABS 과정에 신청하셨습니다.
  notify: true
  message_format : text
  
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    registry-fetch-interval-seconds: 5
